#!/usr/bin/env bash

validate() {
  npm run --silent avram -- -s $@
}

validate avram-schemas/marc-schema.json
validate src/main/resources/marc-schema.json
validate src/main/resources/marc/authority-schema.avram.json
validate src/main/resources/pica-schema.json
validate src/main/resources/pica/avram-k10plus-title.json
validate src/main/resources/unimarc/avram-unimarc.json
validate src/test/resources/pica/schema/pica-schema-extra.json
validate src/test/resources/pica/schema/pica-schema.json
validate src/test/resources/unimarc/avram-unimarc.json
