#!/usr/bin/env bash

validate() {
  npm run --silent avram -- --schema "$1"
}

validate avram-schemas/marc.json
validate avram-schemas/unimarc.json
validate avram-schemas/k10plus-title.json

validate src/main/resources/marc-schema.json    # symlink
validate src/main/resources/marc/authority-schema.avram.json
validate src/main/resources/pica-schema.json

validate src/test/resources/pica/schema/pica-schema-extra.json
validate src/test/resources/pica/schema/pica-schema.json
validate src/test/resources/unimarc/avram-unimarc.json
