#!/bin/bash
set -ueo pipefail

QA_CONTAINER=${QA_CONTAINER:=metadata-qa-marc}

if [ $# == 0 ]; then
  echo "Usage: $0 [options] <command[,command...]>"
  echo
  echo "Run QA catalogue within Docker container '$QA_CONTAINER' (environment"
  echo "variable QA_CONTAINER). Try command 'help' for usage of QA catalogue!"
else
  docker container exec \
    -ti \
    "$QA_CONTAINER" \
    ./qa-catalogue \
    "$@"
fi
