#!/bin/bash
set -ueo pipefail

CONTAINER=${CONTAINER:=metadata-qa-marc}

if [ $# == 0 ]; then
  echo "Usage: $0 [options] <command[,command...]>"
  echo
  echo "Run QA catalogue within Docker container '$CONTAINER' (environment"
  echo "variable CONTAINER). Try command 'help' for usage of QA catalogue!"
else
  docker container exec \
    -ti \
    "$CONTAINER" \
    ./qa-catalogue \
    "$@"
fi
